package libs;


public enum FOOD {
	TROUT, SALMON, TUNA, LOBSTER, SWORDFISH, PIKE, COOKED_CHICKEN, BASS, POTATO_WITH_CHEESE, SHARK, CAVEFISH, SEA_TURTLE, MANTA_RAY, TUNA_POTATO, ROCKTAIL, BARON_SHARK, JUJU_GUMBO
}