package libs;

public enum LOOT {
	FROSTDRAGON_BONES, BLUE_CHARM, CRIMSON_CHARM, GOLD_CHARM, GREEN_CHARM, BLOOD_RUNES, DEATH_RUNES, COINS, CLUE_SCROLL, RUNE_LONGSWORD, WATER_ORB, STARVED_ANCIENT_EFFIGY, PURE_ESSENCE, DRACONIC_VISAGE, GRIMY_RANARR, GRIMY_AVANTOE, GRIMY_IRIT, GRIMY_CADANTINE, SHARK, CLEAN_RANARR, CLEAN_TOADFLAX, CLEAN_TORSTOL, CLEAN_SNAPDRAGON, MAGIC_SEED, TORSTOL_SEED, YEW_SEED, UNCUT_DIAMOND, UNCUT_RUBY, RAW_SHARK, RUNE_BAR, YEW_LOGS, COAL, ADAMANTITE_ORE, RUNITE_ORE, DRAGON_DAGGER, DRAGON_HELM, BATTLESTAFF, RUNE_ARROW, SHIELD_LEFT_HALF, ONYX_BOLTS, LOOP_HALF, TOOTH_HALF, VECNA_SKULL, SARADOMIN_BREW
}