package libs;
	public enum PRAYER {
		// NORMALS
		THICK_SKIN, BURST_OF_STRENGTH, SHARP_EYE, MYSTIC_WILL, ROCK_SKIN, SUPERHUMAN_STRENGTH, IMPROVED_REFLEXES, RAPID_RESTORE, RAPID_HEAL, PROTECT_ITEM, HAWK_EYE, MYSTIC_LORE, STEEL_SKIN, ULTIMATE_STRENGTH, INCREDIBLE_REFLEXES, PROTECT_MAGIC, PROTECT_MISSILES, PROTECT_MELEE, EAGLE_EYE, MYSTIC_MIGHT, CLARITY_OF_THOUGHT;

		// ANCIENTS
	}
