public class PrintResume {

	private final static String OBJECTIVE_DESCR			  = "Offer my skills and work with a team to achieve a common goal while I study at school";
	
	/**
	 * 
	 * Experience info
	 * 
	 */
	private final String EXP_TITLE_AI    			  = "Artificial Intelligence Research";
	private final String EXP_TITLE_DESIGN_LD		  = "Design lead of team(3)";
	private final String EXP_TITLE_CO_LEAD_TB_SIM   = "Co-lead of Thunderbots Simulation league";
	private final String EXP_TITLE_ANDROID_APP      = "Developed and Designed Android App for UBC";
	private final String EXP_TITLE_OPEN_SOURCE_DEV  = "Automated gameplay for MMORPG: Runescape";
	private final String EXP_TITLE_OPEN_SOURCE_DEV2 = "Developed and Designed multiple scripts used by 6k users daily";
	private final String EXP_TITLE_GUI_DESIGN_SWING = "Developed and Designed GUIs for scripts and dev tools";
	private final String EXP_TITLE_API_TOOL_DEV     = "Developed and Designed tools and contributed to API framework";
	
	private final String DESCR_AI                   = "On my own, researching cutting edge algorithms for AI under supervised learning, unsupervised learning, and classification methods. Includes looking at Artificial Neural Networks, fundamental search algorithms, SARSA, Q-Learning, k-means algorithm, k-nearest-neighbour. This is going to be for the simulation of soccer playing agents.";
	private final String DESCR_DESIGN_LD            = "Coming up with the idea and leading the team in breaking down tasks and settings goals using a Scrum management(agile approach) system for a school project. The project takes data sets from Data BC and is using the app engine and android platform to deliver an easy way for families to find them. Designed to be scalable. In touch with dog food companies and dog stores to set up advertising and promotional offers for revenue.";
	private final String DESCR_CO_LEAD_TB_SIM       = "In July 2012 I joined the Thunderbots FC. However, a software lead and I decided to go the full software route due to the hardware rarely being available for testing. Got in touch with a PhD student and a leading AI researcher Alan Mackworth to advise us this year. We're undertaking research and upgrading one of the older code bases to include the best possible AI techniques to win this year's competition";
	private final String DESCR_ANDROID_APP          = "In a second year CS class, along with a partner, I created an android app integrating a basic UI and google maps, gps positioning, and use of the compass";
	private final String DESCR_OPEN_SOURCE_DEV      = "Grabbed the .jar file from Runescape and decrypted it using already available AES decryption algorithms, and then began to reverse engineer the classes to understand the inner workings. An updater was in progress which was to use pattern recognition like neural networks and k-nearest neigbhour algorithms to classify real classes and seperate them from the ones generated by obfuscation. The biggest part was deobfuscating the 1044 classes, many of which were garbage";
	private final String DESCR_OPEN_SOURCE_DEV2     = "Learned a new API to be able to script for a cheating website that obtained over 2 million views monthly. I had designed, developed, and marketed this product over the course of 3 weeks. The outcome was 6k recurring users over the course of a month. I then handed the open source project over to other developers because I had to return to school. A market place was due to come out, and the admins had set the price to be $6.99 for the script. I retained 60% of revenue";
	private final String DESCR_GUI_DESIGN_SWING     = "For the scripts I developed, each had to be presented to those with little to no computer knowledge. The UIs were inuititve and fun. They included my brand and were updated instantly if the community would want a change";
	private final String DESCR_API_TOOL_DEV         = "Tools for quickening the development cycle such as finding game data, searching the API and creating method interfaces for complicated, commonly used procedures";
	
	private final int MONTHS_AI                     = 2;
	private final int MONTHS_DESIGN_LD              = 2;
	private final int MONTHS_CO_LEAD_TB_SIM         = 3;
	private final int MONTHS_ANDROID_APP            = 3;
	private final int MONTHS_OPEN_SOURCE_DEV        = 3;
	private final int MONTHS_OPEN_SOURCE_DEV2       = 6;
	private final int MONTHS_GUI_DESIGN_SWING       = 2;
	private final int MONTHS_API_TOOL_DEV           = 1;
	
	private final int YEARS                         = 0;
	
	
	/**
	 * 
	 * Contact info
	 * 
	 */
	private final String AUTHOR = "@Devon Ash";
	private final String TITLE = "@Computer Scientist";
	private final String EMAIL= "noobaca2@gmail.com";
	private final String CELL = "604-722-3146";
	private final String GITHUB = "http://github.com/TheDash/Resume-Folder";
	
	/**
	 * Education
	 * 
	 */
	private final String SCHOOL_NAME = "University of British Columbia";
	private final String DEGREE = "Computer Science";
	private final int SCHOOL_YEAR = 2;

	/**
	 * Skills
	 * 
	 */
	private final String DATA_STRUCTURE = "Experience optimizing data structure and implementing data structures";
	private final String SORTING        = "Used sorting in various projects, to organize massive files. Heap sorts, binary trees, quicksort in C++";
	private final String NETWORKING     = "Java networking, basic protocols like HTTP, SMTP, FTP, TCP.";
	private final String AI             = "Machine Learning algorithms, working on learning more and learning/understandin theories related to AI/ML";
	private final String DEBUG_TEST     = "Learned how to debug in school using Java Debugger, although most experience came from self developing and many hours of code failure";
	private final String RE_BYTECODE    = "Reverse Engineering Java from bytecode into source and vice versa.";
	private final String PROF_DOC       = "Documentation of code. Whenever code is unclear I tend to document it even if it is not my own.";
	private final String LINUX_MAIN     = "Linux has been main OS for one year";
	private final String LEAD_SMALL_TM  = "Leading small design teams";
	
	private final String DATA_STRUCTURE_EXAMPLE 	= "Speed and real-time reaction was an issue in scripting. The game would progress quickly, so the algorithms used to control the characters had to be efficient in order to compete with real humans";
	private final String SORTING_EXAMPLE 			= "Sorting five massive files containg over 100k elements, each of which had a token:tokenID. Stored in a HashMap. Currently wanting to add the token names into a trie as it is more efficient and offers O(k) time";
	private final String NETWORKING_EXAMPLE 		= "Created a bot that connects to IRC in Java. Working on porting it to C using UDP packets.";
	private final String AI_EXAMPLE     			= "SARSA, Q-Learning, K-Means algorithm, K-Nearest Neighbour, A*, DFS, BFS";
	private final String DEBUG_TEST_EXAMPLE 		= "When I was first starting out my own projects I learned alot about NPEs. I rarely make that mistake anymore because in production code, it would cause all of the customers to get angry and rage on the forums";
	private final String RE_BYTECODE_EXAMPLE  		= "Using the BCEL library I had to inject bytecode and scan for patterns in the bytecode of obfuscated classes in order to recognize them. Once recognized I would inject a getter method to retrieve the data I needed at runtime";
	private final String PROF_DOC_EXAMPLE         = "When trying to understand new code bases, I go through and re-document methods and classes. I write comment on complicated procedures such as when using a BCEL library when most of the things that were going on were confusing if you didn't know how the JVM worked.";
	private final String LINUX_MAIN_EXAMPLE       = "sudo apt-get, | grep, tar -xzvf, man socket, cd, mkdir";
	private final String LEAD_SMALL_TM_EXAMPLE    = "When scripting, I had to get more developers to increase production time. Found two teamates on forums who lived in America. We bonded well and talked on skype as friends and as co-workers.";
	
	private final String VC_GITHUB                = "Github";
	private final int    VC_MONTHS                = 6;
	private final int    VC_YRS                   = 0;
	
	private final String VC_SUBVERSION            = "Subversion";
	private final int    VC_SUB_MONTHS            = 0;
	private final int    VC_SUB_YRS				= 1;
	
	
	public PrintResume() {
		
	}
	
	public void main() {
		
		Resume devonsResume = new Resume();
		
		devonsResume.setAuthor(AUTHOR);
		devonsResume.setTitle(TITLE);
		devonsResume.setEmail(EMAIL);
		devonsResume.setCell(CELL);
		devonsResume.setGithub(GITHUB);
		
		Objective o = new Objective(OBJECTIVE_DESCR);
		
		Experience ai             = new Experience(EXP_TITLE_AI, DESCR_AI, MONTHS_AI, YEARS);
		Experience designLead     = new Experience(EXP_TITLE_DESIGN_LD, DESCR_DESIGN_LD, MONTHS_DESIGN_LD, YEARS);
		Experience coLeadTBSim    = new Experience(EXP_TITLE_CO_LEAD_TB_SIM, DESCR_CO_LEAD_TB_SIM, MONTHS_CO_LEAD_TB_SIM, YEARS);
		Experience androidApp     = new Experience(EXP_TITLE_ANDROID_APP, DESCR_ANDROID_APP, MONTHS_ANDROID_APP, YEARS);
		Experience openSrcDev     = new Experience(EXP_TITLE_OPEN_SOURCE_DEV, DESCR_OPEN_SOURCE_DEV, MONTHS_OPEN_SOURCE_DEV, YEARS);
		Experience openSrcDev2    = new Experience(EXP_TITLE_OPEN_SOURCE_DEV2, DESCR_OPEN_SOURCE_DEV2, MONTHS_OPEN_SOURCE_DEV2, YEARS);
		Experience guiDesignSwing = new Experience(EXP_TITLE_GUI_DESIGN_SWING, DESCR_GUI_DESIGN_SWING, MONTHS_GUI_DESIGN_SWING, YEARS);
		Experience apiToolDev     = new Experience(EXP_TITLE_API_TOOL_DEV, DESCR_API_TOOL_DEV, MONTHS_API_TOOL_DEV, YEARS);
		
		devonsResume.addExperience(ai);
		devonsResume.addExperience(designLead);
		devonsResume.addExperience(coLeadTBSim);
		devonsResume.addExperience(androidApp);
		devonsResume.addExperience(openSrcDev);
		devonsResume.addExperience(openSrcDev2);
		devonsResume.addExperience(guiDesignSwing);
		devonsResume.addExperience(apiToolDev);
		
		School sch = new School(SCHOOL_NAME, DEGREE, SCHOOL_YEAR);

		// Refer to above for skill names
		Skill skill1 = new Skill(DATA_STRUCTURE, DATA_STRUCTURE_EXAMPLE);
		Skill skill2 = new Skill(SORTING, SORTING_EXAMPLE);
		Skill skill3 = new Skill(NETWORKING, NETWORKING_EXAMPLE);
		Skill skill4 = new Skill(AI, AI_EXAMPLE);
		Skill skill5 = new Skill(DEBUG_TEST, DEBUG_TEST_EXAMPLE);
		Skill skill6 = new Skill(RE_BYTECODE, RE_BYTECODE_EXAMPLE);
		Skill skill7 = new Skill(PROF_DOC, PROF_DOC_EXAMPLE);
		Skill skill8 = new Skill(LINUX_MAIN, LINUX_MAIN_EXAMPLE);
		Skill skill9 = new Skill(LEAD_SMALL_TM, LEAD_SMALL_TM_EXAMPLE);
		
		devonsResume.addSkill(skill1);
		devonsResume.addSkill(skill2);
		devonsResume.addSkill(skill3);
		devonsResume.addSkill(skill4);
		devonsResume.addSkill(skill5);
		devonsResume.addSkill(skill6);
		devonsResume.addSkill(skill7);
		devonsResume.addSkill(skill8);
		devonsResume.addSkill(skill9);
		
		VersionControl vc1 = new VersionControl(VC_GITHUB, VC_MONTHS, VC_YRS);
		VersionControl vc2 = new VersionControl(VC_SUBVERSION, VC_SUB_MONTHS, VC_SUB_YRS);

		devonsResume.addVersionControl(vc1);
		devonsResume.addVersionControl(vc2);
		
		devonsResume.setSchool(sch);
		devonsResume.setObjective(o);
	}
	
}